apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: upu58gns6-go 
  janus-idp.io/tekton: upu58gns6-go
  backstage.io/kubernetes-id: upu58gns6-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: upu58gns6-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml